# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blueprint < Formula
  desc "This is a cli application with go and cobra."
  homepage "https://github.com/elliotxx/blueprint"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/blueprint/releases/download/v0.1.0/blueprint_0.1.0_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "0e54e490a6bafcc2df0829c02ce3436048e43b969ca9760a4c08ef7e81b6a4cf"

      def install
        bin.install "blueprint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliotxx/blueprint/releases/download/v0.1.0/blueprint_0.1.0_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "11e0ba23b53473ed3a147a6624dda0ef63e44c9030684eeee42942ebeafbe964"

      def install
        bin.install "blueprint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliotxx/blueprint/releases/download/v0.1.0/blueprint_0.1.0_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c6acf3a18c6545862d2b7fc44767a670429bab2e9e8b37eb8b81b15f26d7d70c"

      def install
        bin.install "blueprint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/blueprint/releases/download/v0.1.0/blueprint_0.1.0_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "0ae6842c6d3c47073ca0d5b317172bac9159da6349274d2005bc3a8648835532"

      def install
        bin.install "blueprint"
      end
    end
  end

  test do
    system "#{bin}/blueprint -V"
  end
end
