# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCliPrototype < Formula
  desc "This is a cli application with go and cobra."
  homepage "https://github.com/elliotxx/go-cli-prototype"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/go-cli-prototype/releases/download/v0.1.8/go-cli-prototype_0.1.8_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "0eee2229547f792bac1adad5dbaffce9325f6cda3ba10142bb0e0b695b71c256"

      def install
        bin.install "go-cli-prototype"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliotxx/go-cli-prototype/releases/download/v0.1.8/go-cli-prototype_0.1.8_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "2616c2534d5ceb9880b6e0b1a5980c22c640fc95e15ada368c1a954d05926c7e"

      def install
        bin.install "go-cli-prototype"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/go-cli-prototype/releases/download/v0.1.8/go-cli-prototype_0.1.8_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "065018eb85295c027f3660b7f4aa0592b38d6a19ced46eece661c8a86ee63e3e"

      def install
        bin.install "go-cli-prototype"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliotxx/go-cli-prototype/releases/download/v0.1.8/go-cli-prototype_0.1.8_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c4cc3a90642f15ba596b4243856edcef7655e00b3d5ab482446025a103340096"

      def install
        bin.install "go-cli-prototype"
      end
    end
  end

  test do
    system "#{bin}/go-cli-prototype -V"
  end
end
