# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCliPrototype < Formula
  desc "This is a cli application with go and cobra."
  homepage "https://github.com/elliotxx/go-cli-prototype"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elliotxx/go-cli-prototype/releases/download/v0.1.6/go-cli-prototype_0.1.6_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f1df6d11cc146f8dab4e8c61826fd03547f6d015fa2da0db21af3e24c0a1d773"

      def install
        bin.install "go-cli-prototype"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/go-cli-prototype/releases/download/v0.1.6/go-cli-prototype_0.1.6_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "46a86050ff712ab0db4508045f2734c675f42eaebc77956134c7e3bcf420b6c2"

      def install
        bin.install "go-cli-prototype"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/go-cli-prototype/releases/download/v0.1.6/go-cli-prototype_0.1.6_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d9e26d8097d9417ef757134cab27af030b3135dac2bc5628613988d2ab22b2a0"

      def install
        bin.install "go-cli-prototype"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliotxx/go-cli-prototype/releases/download/v0.1.6/go-cli-prototype_0.1.6_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "8f9989af792f415a2c0c5e82063759387c88796a66d04d16f367d9fcf8a12cdd"

      def install
        bin.install "go-cli-prototype"
      end
    end
  end

  test do
    system "#{bin}/go-cli-prototype -V"
  end
end
