# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdfmt < Formula
  desc "A Markdown formatter that follow the CommonMark. Like gofmt, but for Markdown."
  homepage "https://github.com/elliotxx/mdfmt"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elliotxx/mdfmt/releases/download/v0.3.3/mdfmt_0.3.3_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "7b2d809208f7a50acffaf245228497363f6f7162c99ad74b5a7e9f2c8297ae80"

      def install
        bin.install "mdfmt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/mdfmt/releases/download/v0.3.3/mdfmt_0.3.3_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e074c7d38bdb79649bb338afc73c5a00f0eb1064ab44e89b333827c3abcda6d2"

      def install
        bin.install "mdfmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/mdfmt/releases/download/v0.3.3/mdfmt_0.3.3_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ebfc3dbd8f0177f3887669324a82b35ef2b6e5588dd95d693245ab6f2dde3b55"

      def install
        bin.install "mdfmt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliotxx/mdfmt/releases/download/v0.3.3/mdfmt_0.3.3_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "4c48440b3f4347c344f8639ecd7ab7110821ff8459095388f9a80c59b3c107ff"

      def install
        bin.install "mdfmt"
      end
    end
  end

  test do
    system "#{bin}/mdfmt -V"
  end
end
