# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdfmt < Formula
  desc "A Markdown formatter that follow the CommonMark. Like gofmt, but for Markdown."
  homepage "https://github.com/elliotxx/mdfmt"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/elliotxx/mdfmt/releases/download/v0.2.3/mdfmt_0.2.3_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "838062ac5e8bf01390d8d08b9c9558c1ca1ed566f41edb1306337aa743549316"

      def install
        bin.install "mdfmt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/mdfmt/releases/download/v0.2.3/mdfmt_0.2.3_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "2202277ad69eb71562fedc300a3b66edc4e77a3683619b0e7560505689167d38"

      def install
        bin.install "mdfmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliotxx/mdfmt/releases/download/v0.2.3/mdfmt_0.2.3_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9902cb725c7409becf89276e9ba0e9e0b7cc9902f67e48b807e38e4eac5815f9"

      def install
        bin.install "mdfmt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/mdfmt/releases/download/v0.2.3/mdfmt_0.2.3_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b745e2d95d327a708bf851227e934a1298f8bf49e8ef6869fc74c1c974afb510"

      def install
        bin.install "mdfmt"
      end
    end
  end

  test do
    system "#{bin}/mdfmt -V"
  end
end
