# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osp < Formula
  desc "Open Source Software Pilot"
  homepage "https://github.com/elliotxx/osp"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/osp/releases/download/v0.1.4/osp_0.1.4_darwin_amd64.tar.gz"
      sha256 "f145c54808e630ad1221ee50076c7aa24b193be586d9fddc067f09640dd6c08e"

      def install
        bin.install "osp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliotxx/osp/releases/download/v0.1.4/osp_0.1.4_darwin_arm64.tar.gz"
      sha256 "f07a5ca594c74080899ced4f0e4344e43d47a6583154a5b0593d338785079f32"

      def install
        bin.install "osp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/elliotxx/osp/releases/download/v0.1.4/osp_0.1.4_linux_amd64.tar.gz"
        sha256 "c63a1bd45aceae07d875dc70e241cc711bb4dab199097c15fff01efd02cff096"

        def install
          bin.install "osp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/elliotxx/osp/releases/download/v0.1.4/osp_0.1.4_linux_arm64.tar.gz"
        sha256 "2c5d172f00af12c6a21337d24a44d77fd515e7d151061c2b67d11a37e145f375"

        def install
          bin.install "osp"
        end
      end
    end
  end

  test do
    system "#{bin}/osp --version"
  end
end
