# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osp < Formula
  desc "Open Source Software Pilot"
  homepage "https://github.com/elliotxx/osp"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/osp/releases/download/v0.1.11/osp_0.1.11_darwin_amd64.tar.gz"
      sha256 "fdc7123c9f96deaf4e3c9498593461bf4df96a0f40c585815181ddc152384a09"

      def install
        bin.install "osp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliotxx/osp/releases/download/v0.1.11/osp_0.1.11_darwin_arm64.tar.gz"
      sha256 "6db46f723531ee6f5d66fd818b58f2c6261b5d07d1d14da4400382e63bfd23b2"

      def install
        bin.install "osp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/elliotxx/osp/releases/download/v0.1.11/osp_0.1.11_linux_amd64.tar.gz"
        sha256 "624c88c439b75bc01cffa5476fb48b39787a3d15a3d48ae0d483933e3f1099a2"

        def install
          bin.install "osp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/elliotxx/osp/releases/download/v0.1.11/osp_0.1.11_linux_arm64.tar.gz"
        sha256 "d6877c87d1a10e79137717cf8a274badb917de6f92275315d6dc52ea62123fea"

        def install
          bin.install "osp"
        end
      end
    end
  end

  test do
    system "#{bin}/osp --version"
  end
end
