# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osp < Formula
  desc "Open Source Software Pilot"
  homepage "https://github.com/elliotxx/osp"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliotxx/osp/releases/download/v0.1.2/osp_0.1.2_darwin_amd64.tar.gz"
      sha256 "520040a8202cf27c84990445581f8c1120a2b3a390dd701e2139b425251d2c50"

      def install
        bin.install "osp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliotxx/osp/releases/download/v0.1.2/osp_0.1.2_darwin_arm64.tar.gz"
      sha256 "bf66bfd534f04160bef7bf1e8457b9cf9156ad28f2cc8f8d16efcdd52557218a"

      def install
        bin.install "osp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/elliotxx/osp/releases/download/v0.1.2/osp_0.1.2_linux_amd64.tar.gz"
        sha256 "8420865c6283abed20642efe343c8102f382f1dcf0437deab76af32774899312"

        def install
          bin.install "osp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/elliotxx/osp/releases/download/v0.1.2/osp_0.1.2_linux_arm64.tar.gz"
        sha256 "6d8b974e01d6d72e4b988111f7548b9a96c702c4ec1458c211460b225f2054af"

        def install
          bin.install "osp"
        end
      end
    end
  end

  test do
    system "#{bin}/osp --version"
  end
end
